-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity topo_HHbbWW_1mu_v5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    muons_0 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_3 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_4 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_6 : IN STD_LOGIC_VECTOR (63 downto 0);
    muons_7 : IN STD_LOGIC_VECTOR (63 downto 0);
    jets_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    jets_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    egammas_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    taus_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    et : IN STD_LOGIC_VECTOR (31 downto 0);
    ht : IN STD_LOGIC_VECTOR (31 downto 0);
    etmiss : IN STD_LOGIC_VECTOR (31 downto 0);
    htmiss : IN STD_LOGIC_VECTOR (31 downto 0);
    ethfmiss : IN STD_LOGIC_VECTOR (31 downto 0);
    hthfmiss : IN STD_LOGIC_VECTOR (31 downto 0);
    topo_score : OUT STD_LOGIC_VECTOR (15 downto 0);
    topo_score_ap_vld : OUT STD_LOGIC );
end;


architecture behav of topo_HHbbWW_1mu_v5 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "topo_HHbbWW_1mu_v5_topo_HHbbWW_1mu_v5,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx690t-ffg1927-2,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=24.955250,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=755,HLS_SYN_LUT=51285,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal input_scaled_scaleNNInputs_fu_211_ap_return : STD_LOGIC_VECTOR (332 downto 0);
    signal input_scaled_reg_431 : STD_LOGIC_VECTOR (332 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal input_scaled_scaleNNInputs_fu_211_ap_ready : STD_LOGIC;
    signal input_scaled_scaleNNInputs_fu_211_p_read : STD_LOGIC_VECTOR (11 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read1 : STD_LOGIC_VECTOR (8 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read2 : STD_LOGIC_VECTOR (8 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read3 : STD_LOGIC_VECTOR (9 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read4 : STD_LOGIC_VECTOR (3 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read5 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read6 : STD_LOGIC_VECTOR (8 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read7 : STD_LOGIC_VECTOR (9 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read8 : STD_LOGIC_VECTOR (3 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read9 : STD_LOGIC_VECTOR (10 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read10 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read11 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read12 : STD_LOGIC_VECTOR (10 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read13 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read14 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read15 : STD_LOGIC_VECTOR (10 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read16 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read17 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read18 : STD_LOGIC_VECTOR (10 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read19 : STD_LOGIC_VECTOR (7 downto 0);
    signal input_scaled_scaleNNInputs_fu_211_p_read20 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_TOPO_project_fu_236_ap_start : STD_LOGIC;
    signal grp_TOPO_project_fu_236_ap_done : STD_LOGIC;
    signal grp_TOPO_project_fu_236_ap_idle : STD_LOGIC;
    signal grp_TOPO_project_fu_236_ap_ready : STD_LOGIC;
    signal grp_TOPO_project_fu_236_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp32 : BOOLEAN;
    signal grp_TOPO_project_fu_236_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_ignoreCallOp33 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component topo_HHbbWW_1mu_v5_scaleNNInputs IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (11 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (3 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (8 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (3 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (10 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (332 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component topo_HHbbWW_1mu_v5_TOPO_project IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dropout_input_val1 : IN STD_LOGIC_VECTOR (332 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    input_scaled_scaleNNInputs_fu_211 : component topo_HHbbWW_1mu_v5_scaleNNInputs
    port map (
        ap_ready => input_scaled_scaleNNInputs_fu_211_ap_ready,
        p_read => input_scaled_scaleNNInputs_fu_211_p_read,
        p_read1 => input_scaled_scaleNNInputs_fu_211_p_read1,
        p_read2 => input_scaled_scaleNNInputs_fu_211_p_read2,
        p_read3 => input_scaled_scaleNNInputs_fu_211_p_read3,
        p_read4 => input_scaled_scaleNNInputs_fu_211_p_read4,
        p_read5 => input_scaled_scaleNNInputs_fu_211_p_read5,
        p_read6 => input_scaled_scaleNNInputs_fu_211_p_read6,
        p_read7 => input_scaled_scaleNNInputs_fu_211_p_read7,
        p_read8 => input_scaled_scaleNNInputs_fu_211_p_read8,
        p_read9 => input_scaled_scaleNNInputs_fu_211_p_read9,
        p_read10 => input_scaled_scaleNNInputs_fu_211_p_read10,
        p_read11 => input_scaled_scaleNNInputs_fu_211_p_read11,
        p_read12 => input_scaled_scaleNNInputs_fu_211_p_read12,
        p_read13 => input_scaled_scaleNNInputs_fu_211_p_read13,
        p_read14 => input_scaled_scaleNNInputs_fu_211_p_read14,
        p_read15 => input_scaled_scaleNNInputs_fu_211_p_read15,
        p_read16 => input_scaled_scaleNNInputs_fu_211_p_read16,
        p_read17 => input_scaled_scaleNNInputs_fu_211_p_read17,
        p_read18 => input_scaled_scaleNNInputs_fu_211_p_read18,
        p_read19 => input_scaled_scaleNNInputs_fu_211_p_read19,
        p_read20 => input_scaled_scaleNNInputs_fu_211_p_read20,
        ap_return => input_scaled_scaleNNInputs_fu_211_ap_return,
        ap_rst => ap_rst);

    grp_TOPO_project_fu_236 : component topo_HHbbWW_1mu_v5_TOPO_project
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_TOPO_project_fu_236_ap_start,
        ap_done => grp_TOPO_project_fu_236_ap_done,
        ap_idle => grp_TOPO_project_fu_236_ap_idle,
        ap_ready => grp_TOPO_project_fu_236_ap_ready,
        dropout_input_val1 => input_scaled_reg_431,
        ap_return => grp_TOPO_project_fu_236_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    grp_TOPO_project_fu_236_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_TOPO_project_fu_236_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    grp_TOPO_project_fu_236_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TOPO_project_fu_236_ap_ready = ap_const_logic_1)) then 
                    grp_TOPO_project_fu_236_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                input_scaled_reg_431 <= input_scaled_scaleNNInputs_fu_211_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_TOPO_project_fu_236_ap_start <= grp_TOPO_project_fu_236_ap_start_reg;
    input_scaled_scaleNNInputs_fu_211_p_read <= ht(12 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read1 <= muons_0(18 downto 10);
    input_scaled_scaleNNInputs_fu_211_p_read10 <= jets_0(18 downto 11);
    input_scaled_scaleNNInputs_fu_211_p_read11 <= jets_0(26 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read12 <= jets_1(11 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read13 <= jets_1(18 downto 11);
    input_scaled_scaleNNInputs_fu_211_p_read14 <= jets_1(26 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read15 <= jets_2(11 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read16 <= jets_2(18 downto 11);
    input_scaled_scaleNNInputs_fu_211_p_read17 <= jets_2(26 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read18 <= jets_3(11 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read19 <= jets_3(18 downto 11);
    input_scaled_scaleNNInputs_fu_211_p_read2 <= muons_0(31 downto 23);
    input_scaled_scaleNNInputs_fu_211_p_read20 <= jets_3(26 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read3 <= muons_0(10 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read4 <= muons_0(22 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read5 <= muons_1(17 downto 10);
    input_scaled_scaleNNInputs_fu_211_p_read6 <= muons_1(31 downto 23);
    input_scaled_scaleNNInputs_fu_211_p_read7 <= muons_1(10 - 1 downto 0);
    input_scaled_scaleNNInputs_fu_211_p_read8 <= muons_1(22 downto 19);
    input_scaled_scaleNNInputs_fu_211_p_read9 <= jets_0(11 - 1 downto 0);
    topo_score <= grp_TOPO_project_fu_236_ap_return;

    topo_score_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            topo_score_ap_vld <= ap_const_logic_1;
        else 
            topo_score_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
